blank_issues_enabled: false
contact_links:
    - name: ğŸ¤” Feature Requests & questions
      url: https://github.com/chiangs/waffle-chart/discussions
      about: Please ask and answer questions here.
